spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      # 解决与swagger的冲突
      matching-strategy: ant_path_matcher
server:
  port: 8080
swagger:
  base-package: info.jiatu.jtlsp.web
  title: ${spring.application.name}
  author-name: jtlsp
logback:
  path: .logs
  service-name: ${spring.application.name}
logging:
  config: classpath:logback/logback-spring.xml