spring:
  profiles:
    active: local
server:
  port: 8080
swagger:
  base-package: info.jiatu.jtlsp.template
  title: ${spring.application.name}
  author-name: jtlsp
logback:
  path: ./usr/verticles/logs
  service-name: ${spring.application.name}
logging:
  config: classpath:logback/logback-spring.xml